import "@/styles/globals.css"
import { Metadata } from "next";

import { fontSans } from "../lib/fonts"
import { cn } from "../lib/utils"
import { ThemeProvider } from "next-themes";
import { ThemeWrapper } from "@/components/ui-examples/theme-wrapper";
import { TailwindIndicator } from "@/components/ui-examples/tailwind-indicator";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head/>
        <body
          className={cn(
            "bg-background h-full font-sans antialiased",
            fontSans.variable
          )}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ThemeWrapper className="h-full">
                {children}
              <TailwindIndicator />
            </ThemeWrapper>
          </ThemeProvider>
        </body>
      </html>
    </>
  )
}